export const TYPES = {
    LAYOUT_ITEM_CREATOR: Symbol.for("LAYOUT_ITEM_CREATOR"),
    LAYOUT_ITEM_REPOSITORY: Symbol.for("LAYOUT_ITEM_REPOSITORY"),
    LAYOUT_ITEMS_FINDER: Symbol.for("LAYOUT_ITEMS_FINDER")
}